class PackSounds expands actor;

//#exec OBJ LOAD FILE=..\sounds\AllDialog.uax PACKAGE=HPSounds.AllDialog
#exec OBJ LOAD FILE=..\sounds\Critters_sfx.uax PACKAGE=HPSounds.Critters_sfx
#exec OBJ LOAD FILE=..\sounds\FootSteps.uax PACKAGE=HPSounds.FootSteps
#exec OBJ LOAD FILE=..\sounds\General.uax PACKAGE=HPSounds.General
#exec OBJ LOAD FILE=..\sounds\HAR_emotes.uax PACKAGE=HPSounds.Har_Emotes
#exec OBJ LOAD FILE=..\sounds\Har_inc.uax PACKAGE=HPSounds.Har_inc
#exec OBJ LOAD FILE=..\sounds\hub1_sfx.uax PACKAGE=HPSounds.hub1_sfx
#exec OBJ LOAD FILE=..\sounds\Magic_sfx.uax PACKAGE=HPSounds.Magic_sfx
#exec OBJ LOAD FILE=..\sounds\menu_sfx.uax PACKAGE=HPSounds.menu_sfx
#exec OBJ LOAD FILE=..\sounds\Exec_demo_level_SFX.uax PACKAGE=HPSounds.Exec_demo_level_SFX
#exec OBJ LOAD FILE=..\sounds\Ch2Skurge.uax PACKAGE=HPSounds.Ch2Skurge
#exec OBJ LOAD FILE=..\sounds\Adv1Willow.uax PACKAGE=HPSounds.Adv1Willow
#exec OBJ LOAD FILE=..\sounds\Ch1Rictusempra.uax PACKAGE=HPSounds.Ch1Rictusempra
#exec OBJ LOAD FILE=..\sounds\Adv11_COS.uax PACKAGE=HPSounds.Adv11_COS
#exec OBJ LOAD FILE=..\sounds\cocacola.uax PACKAGE=HPSounds.cocacola
#exec OBJ LOAD FILE=..\sounds\Ch6WizardCard.uax PACKAGE=HPSounds.Ch6WizardCard
#exec OBJ LOAD FILE=..\sounds\Adv12Chamber.uax PACKAGE=HPSounds.Adv12Chamber
#exec OBJ LOAD FILE=..\sounds\Adv9Aragog.uax PACKAGE=HPSounds.Adv9Aragog
#exec OBJ LOAD FILE=..\sounds\Adv8Forest.uax PACKAGE=HPSounds.Adv8Forest
#exec OBJ LOAD FILE=..\sounds\Adv7SlythComRoom.uax PACKAGE=HPSounds.Adv7SlythComRoom
#exec OBJ LOAD FILE=..\sounds\Adv4Greenhouse.uax PACKAGE=HPSounds.Adv4Greenhouse
#exec OBJ LOAD FILE=..\sounds\Ch3Diffindo.uax PACKAGE=HPSounds.Ch3Diffindo
#exec OBJ LOAD FILE=..\sounds\Adv3DungeonQuest.uax PACKAGE=HPSounds.Adv3DungeonQuest
#exec OBJ LOAD FILE=..\sounds\PrivetDr.uax PACKAGE=HPSounds.PrivetDr
#exec OBJ LOAD FILE=..\sounds\Quidditch.uax PACKAGE=HPSounds.Quidditch_sfx
#exec OBJ LOAD FILE=..\sounds\Music_Events.uax PACKAGE=HPSounds.Music_Events
#exec OBJ LOAD FILE=..\sounds\Dueling.uax PACKAGE=HPSounds.Dueling