[URL]
Protocol=unreal
ProtocolDescription=Unreal Protocol
Name=Player
Map=autoplay.unr
LocalMap=Startup.unr
Host=
Portal=
MapExt=unr
SaveExt=usa
Port=7777
Class=Engine.Playerpawn

[FirstRun]
FirstRun=0
Reconfig=1
ForceSoftware=0

[Engine.Engine]
EASplashWaitTime=1.5
WBSplashWaitTime=1.5
GameRenderDevice=VulkanDrv.VulkanRenderDevice
AudioDevice=ALAudio.ALAudioSubsystem
NetworkDevice=IpDrv.TcpNetDriver
DemoRecordingDevice=Engine.DemoRecDriver
;Console=UWindow.WindowConsole
Console=HGame.HPConsole
Language=int
GameEngine=Engine.GameEngine
EditorEngine=Editor.EditorEngine
WindowedRenderDevice=VulkanDrv.VulkanRenderDevice
RenderDevice=VulkanDrv.VulkanRenderDevice
DefaultGame=Engine.GameInfo
DefaultServerGame=Engine.GameInfo
ViewportManager=SDLDrv.SDLClient
Render=Render.Render
Input=Engine.Input
Canvas=Engine.Canvas
RunCount=1

[Core.System]
PurgeCacheDays=30
SavePath=/Users/mike/Code/Default/hp2/vk-smoke/Home/Library/Application Support/Harry Potter 2/User/Save/
CachePath=/Users/mike/Code/Default/hp2/vk-smoke/Home/Library/Application Support/Harry Potter 2/User/Cache/
CacheExt=.uxx
Paths=../System/*.u
Paths=../Maps/*.unr
Paths=../Textures/*.utx
Paths=../Sounds/*.uax
Paths=../Music/*.umx
Paths=/Users/mike/Code/Default/hp2/vk-smoke/Home/Library/Application Support/Harry Potter 2/User/Save/*.usa
Suppress=DevLoad
Suppress=DevSave
Suppress=DevNetTraffic
Suppress=DevGarbage
Suppress=DevKill
Suppress=DevReplace
Suppress=DevSound
Suppress=DevCompile
Suppress=DevBind
Suppress=DevBsp
;Suppress=ScriptLog
Suppress=ScriptWarning
;Suppress=Log
Suppress=Localization

[Engine.GameEngine]
CacheSizeMegs=4
UseSound=True
FrameRateLimit=60.000000
ServerActors=UWeb.WebServer

[WinDrv.WindowsClient]
WindowedViewportX=800
WindowedViewportY=600
WindowedColorBits=16
FullscreenViewportX=800
FullscreenViewportY=600
FullscreenColorBits=16
Brightness=0.400000
MipFactor=1.000000
UseDirectDraw=True
UseJoystick=True
CaptureMouse=True
StartupFullscreen=True
CurvedSurfaces=False
LowDetailTextures=False
ScreenFlashes=True
NoLighting=False
SlowVideoBuffering=True
DeadZoneXYZ=True
DeadZoneRUV=False
InvertVertical=False
ScaleXYZ=1000.0
ScaleRUV=2000.0
MinDesiredFrameRate=30.0
Decals=True
NoDynamicLights=False
ParticleDensity=1

[XDrv.XClient]
WindowedViewportX=640
WindowedViewportY=480
WindowedColorBits=16
FullscreenViewportX=640
FullscreenViewportY=480
FullscreenColorBits=32
Brightness=0.500000
MipFactor=1.000000
SlowVideoBuffering=False
StartupFullscreen=True
CurvedSurfaces=False
CaptureMouse=True
LowDetailTextures=False
ScreenFlashes=True
NoLighting=False
DeadZoneXYZ=True
DeadZoneRUV=False
InvertVertical=False
ScaleXYZ=1000.0
ScaleRUV=2000.0
MinDesiredFrameRate=30.0

[Engine.Player]
ConfiguredInternetSpeed=2600
ConfiguredLanSpeed=20000

[Audio.GenericAudioSubsystem]
UseFilter=True
UseSurround=False
UseStereo=True
UseCDMusic=False
UseDigitalMusic=False
UseSpatial=False
UseReverb=False
Use3dHardware=False
LowSoundQuality=False
ReverseStereo=False
Latency=40
OutputRate=22050Hz
Channels=16
MusicVolume=128
SoundVolume=200
AmbientFactor=0.7

[ALAudio.ALAudioSubsystem]
UseEAX=False
CompatibilityMode=False
UsePrecache=False
ReverseStereo=False
Channels=32
MusicVolume=0.5
SoundVolume=0.9
DopplerFactor=1
RollOff=1

[IpDrv.TcpNetDriver]
AllowDownloads=True
ConnectionTimeout=15.0
InitialConnectTimeout=300.0
AckTimeout=1.0
KeepAliveTime=0.2
MaxClientRate=20000
SimLatency=0
RelevantTimeout=5.0
SpawnPrioritySeconds=1.0
ServerTravelPause=4.0
NetServerMaxTickRate=20
LanServerMaxTickRate=35
DownloadManagers=IpDrv.HTTPDownload
DownloadManagers=Engine.ChannelDownload

[IpDrv.HTTPDownload]
RedirectToURL=
ProxyServerHost=
ProxyServerPort=3128
UseCompression=True

[Engine.DemoRecDriver]
DemoSpectatorClass=HGame.harry
MaxClientRate=25000
ConnectionTimeout=15.0
InitialConnectTimeout=500.0
AckTimeout=1.0
KeepAliveTime=1.0
SimLatency=0
RelevantTimeout=5.0
SpawnPrioritySeconds=1.0
ServerTravelPause=4.0
NetServerMaxTickRate=60
LanServerMaxTickRate=60

[Engine.GameReplicationInfo]
ServerName=Another UT Server
ShortName=UT Server

[IpDrv.TcpipConnection]
SimPacketLoss=0
SimLatency=0

[IpServer.UdpServerQuery]
GameName=ut

[IpDrv.UdpBeacon]
DoBeacon=True
BeaconTime=0.50
BeaconTimeout=5.0
BeaconProduct=ut

[SoftDrv.SoftwareRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=True
Coronas=False
HighDetailActors=False
HighResTextureSmooth=True
LowResTextureSmooth=False
FastTranslucency=True

[GlideDrv.GlideRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailBias=-1.500000
RefreshRate=60Hz
DetailTextures=True
FastUglyRefresh=False
ScreenSmoothing=True
Resolution=Default

[MetalDrv.MetalRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailTextures=False

[OpenGLDrv.OpenGLRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailTextures=True

[D3DDrv.D3DRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=True
Coronas=True
HighDetailActors=True
UseMipmapping=True
UseTrilinear=False
UseMultitexture=True
UsePageFlipping=True
UsePalettes=True
UseFullscreen=true
UseGammaCorrection=True
DetailTextures=False
Use3dfx=False
UseTripleBuffering=True
UsePrecache=True
Use32BitTextures=False

[SglDrv.SglRenderDevice]
Translucency=True
VolumetricLighting=False
ShinySurfaces=False
Coronas=True
HighDetailActors=False
ColorDepth=32
DetailTextures=False
FastUglyRefresh=False
TextureDetailBias=Near
VertexLighting=False

[Editor.EditorEngine]
UseSound=True
CacheSizeMegs=6
GridEnabled=True
SnapVertices=True
SnapDistance=10.000000
GridSize=(X=16.000000,Y=16.000000,Z=16.000000)
RotGridEnabled=True
RotGridSize=(Pitch=1024,Yaw=1024,Roll=1024)
GameCommandLine=-log
FovAngleDegrees=90.000000
GodMode=True
AutoSave=False
AutoSaveTimeMinutes=5
AutoSaveIndex=6
C_WorldBox=(R=0,G=0,B=107,A=0)
C_GroundPlane=(R=0,G=0,B=63,A=0)
C_GroundHighlight=(R=0,G=0,B=127,A=0)
C_BrushWire=(R=255,G=63,B=63,A=0)
C_Pivot=(R=0,G=255,B=0,A=0)
C_Select=(R=0,G=0,B=127,A=0)
C_AddWire=(R=127,G=127,B=255,A=0)
C_SubtractWire=(R=255,G=192,B=63,A=0)
C_GreyWire=(R=163,G=163,B=163,A=0)
C_Invalid=(R=163,G=163,B=163,A=0)
C_ActorWire=(R=127,G=63,B=0,A=0)
C_ActorHiWire=(R=255,G=127,B=0,A=0)
C_White=(R=255,G=255,B=255,A=0)
C_SemiSolidWire=(R=127,G=255,B=0,A=0)
C_NonSolidWire=(R=63,G=192,B=32,A=0)
C_WireGridAxis=(R=119,G=119,B=119,A=0)
C_ActorArrow=(R=163,G=0,B=0,A=0)
C_ScaleBox=(R=151,G=67,B=11,A=0)
C_ScaleBoxHi=(R=223,G=149,B=157,A=0)
C_Mover=(R=255,G=0,B=255,A=0)
C_OrthoBackground=(R=163,G=163,B=163,A=0)
C_Current=(R=0,G=0,B=0,A=0)
C_BrushVertex=(R=0,G=0,B=0,A=0)
C_BrushSnap=(R=0,G=0,B=0,A=0)
C_Black=(R=0,G=0,B=0,A=0)
C_Mask=(R=0,G=0,B=0,A=0)
C_WireBackground=(R=0,G=0,B=0,A=0)
C_ZoneWire=(R=0,G=0,B=0,A=0)
EditPackages=Core
EditPackages=Engine
EditPackages=Editor
EditPackages=UWindow
EditPackages=Fire
EditPackages=UnrealShare
EditPackages=HPSounds
EditPackages=HPModels
EditPackages=HPParticle
EditPackages=HProps
EditPackages=HGame

[Engine.GameInfo]
bLowGore=False
bVeryLowGore=False

[UBrowser.UBrowserMainClientWindow]
LANTabName=UBrowserLAN
ServerListNames[0]=UBrowserUT
ServerListNames[1]=UBrowserLAN
ServerListNames[2]=UBrowserPopulated
ServerListNames[3]=UBrowserDeathmatch
ServerListNames[4]=UBrowserTeamGames
ServerListNames[5]=UBrowserCTF
ServerListNames[6]=UBrowserDOM
ServerListNames[7]=UBrowserAS
ServerListNames[8]=UBrowserLMS
ServerListNames[9]=UBrowserAll
ServerListNames[10]=None
ServerListNames[11]=None
ServerListNames[12]=None
ServerListNames[13]=None
ServerListNames[14]=None
ServerListNames[15]=None
ServerListNames[16]=None
ServerListNames[17]=None
ServerListNames[18]=None
ServerListNames[19]=None

[UBrowserUT]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,bCompatibleServersOnly=True

[UBrowserLAN]
ListFactories[0]=UBrowser.UBrowserLocalFact,BeaconProduct=ut
URLAppend=?LAN
AutoRefreshTime=10
bNoAutoSort=True

[UWeb.WebServer]
Applications[0]=UTServerAdmin.UTServerAdmin
ApplicationPaths[0]=/ServerAdmin
Applications[1]=UTServerAdmin.UTImageServer
ApplicationPaths[1]=/images
DefaultApplication=0
bEnabled=False

[UBrowser.UBrowserHTTPClient]
ProxyServerAddress=
ProxyServerPort=

[UTServerAdmin.UTServerAdmin]
AdminUsername=admin
AdminPassword=admin

[optionsettings]
MaxRes=1024
shadowsOn=true

[SiS 6326]

[4153.25142]
Softwareonly=true
topRes=1024
shadows=true

[Verite Rendition 2100/2200]

[4451.8192]
Softwareonly=true
topRes=1024
shadows=true

[Riva 128 nVidia]

[4318.24]
Softwareonly=true
topRes=1024
shadows=true

[also Riva 128 nVidia]

[4318.25]
Softwareonly=true
topRes=1024
shadows=true

[Riva 128 STB]

[4818.24]
Softwareonly=true
topRes=1024
shadows=true

[also Riva 128 STB]

[4818.25]
Softwareonly=true
topRes=1024
shadows=true

[Savage 4]

[4354.35362]
Softwareonly=true
topRes=1024
shadows=true

[Matrox Mystique]

[4139.1306]
Softwareonly=true
topRes=1024
shadows=true

[Matrox Millenium I]

[4139.1305]
Softwareonly=true
topRes=1024
shadows=true

[Matrox Millenium II]

[4139.1307]
Softwareonly=true
topRes=1024
shadows=true

[also Matrox Millenium II]

[4139.1311]
Softwareonly=true
topRes=1024
shadows=true

[Matrox G200]

[4139.1313]
Softwareonly=true
topRes=1024
shadows=true

[Matrox G400]

[4139.1317]
Softwareonly=true
topRes=1024
shadows=true

[Voodoo 3]

[4634.5]
Softwareonly=true
topRes=1024
shadows=true

[Diamond Stealth III/Speedstar A200]

[ 21299.35362 ]
Softwareonly=true
topRes=1024
shadows=true

[ RAGE IIC AGP ]

[4098.18263]
Softwareonly=true
topRes=1024
shadows=true

[ ATI 3D Rage Pro  ]

[4098.18242]
Softwareonly=true
topRes=1024
shadows=true

[HGame.baseConsole]
bDebugMode=true
bUseSystemFonts=True

[VulkanDrv.VulkanRenderDevice]
VkExclusiveFullscreen=False
VkDebug=False
VkDeviceIndex=0
LightMode=Normal
GammaMode=D3D9
AntialiasMode=Off
LODBias=0
BloomAmount=128
Bloom=False
OccludeLines=False
HdrScale=128
Hdr=False
GrayFormula=1
Saturation=255
Contrast=128
LinearBrightness=128
GammaOffsetBlue=0
GammaOffsetGreen=0
GammaOffsetRed=0
GammaOffset=0
GammaCorrectScreenshots=True
UsePrecache=True
UseVSync=True
DetailTextures=True
DescFlags=0
Description=
HighDetailActors=True
Coronas=True
ShinySurfaces=True
VolumetricLighting=True

[HGame.HPConsole]
RootWindow=UWindow.UWindowRootWindow
MouseScale=0.6
ShowDesktop=False
bShowConsole=False
UWindowKey=IK_None

[UWindow.WindowConsole]
ConsoleKey=192

