#!/usr/bin/env python3
"""Save-format golden-corpus contracts for HP2 `.usa` saves (UE1 package v79).

Build/repair_save.py never parses save bytes itself: it stages an isolated
profile and drives the native Unreal loader/writer (`UGameEngine::SaveGame`,
`UnGame.cpp`) over them. This suite exercises the same format through the two
refactor-free module seams the repository already ships:

* ``repair_save``         -- slot-naming contract (``SAVE_NAME``) and, behind
                             an opt-in gate, the real native save writer.
* ``package79_reference`` -- the canonical Python reader of the exact
                             package-79 layout the native loader enforces
                             (tag 0x9E2A83C1, version 79, licensee 0).

The corpus under Tests/Fixtures/save-format-golden/ is generated by
:func:`build_corpus` below and must stay byte-identical to it; MANIFEST.json
is the executable specification every test iterates.

Everything here is deterministic: fixed GUIDs, synthetic arithmetic payloads,
no network, no wall clock, locale-independent byte parsing.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import struct
import sys
import tempfile
import unittest

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPOSITORY_ROOT / "Build"))

import package79_reference as p79  # noqa: E402
import repair_save  # noqa: E402

FIXTURE_DIR = REPOSITORY_ROOT / "Tests" / "Fixtures" / "save-format-golden"

# Literal versioned-header contract shared with the native loader
# (PackageAudit.cpp / UnPackage.cpp) and package79_reference.
PACKAGE_TAG = p79.PACKAGE_TAG
PACKAGE_VERSION = p79.PACKAGE_VERSION
LICENSEE_VERSION = p79.LICENSEE_VERSION
VERSION_WORD = PACKAGE_VERSION | (LICENSEE_VERSION << 16)

# Synthetic placeholder values; the package-79 reader does not constrain them.
SYNTHETIC_NAME_FLAGS = 0x07001000
SYNTHETIC_OBJECT_FLAGS = 0x001C0001  # public + load-for-client/server/edit shape
FIXED_GUID = (0x2144F1A6, 0x8C7D4B2E, 0x9A51C03D, 0x6E2F8B17)

HEADER_SIZE = 64  # 56-byte summary + one 8-byte generation record

# Generic UE1 class/package identifiers; no game-data content.
_SAVE_NAMES = ("Core", "Package", "Engine", "Class", "Level", "PersistentLevel")
_SAVE_IMPORTS = (
    ("Core", "Package", 0, "Engine"),  # Core.Package Engine
    ("Engine", "Class", -1, "Level"),  # Engine.Class Level (class of the export)
)
_LEVEL_EXPORT = {
    "class_ref": -2,  # -> Engine.Class Level import above
    "super_ref": 0,
    "outer_ref": 0,  # rooted at the package itself
    "name": "PersistentLevel",
}


def _synthetic_payload(size: int = 96) -> bytes:
    """Deterministic stand-in for serialized actor data."""
    return bytes((index * 37 + 11) & 0xFF for index in range(size))


def _name_record(text: str, *, utf16: bool) -> bytes:
    if utf16:
        units = len(text) + 1
        return (
            p79.encode_compact_index(-units)
            + text.encode("utf-16-le")
            + b"\0\0"
            + struct.pack("<I", SYNTHETIC_NAME_FLAGS)
        )
    encoded = text.encode("latin-1")
    return (
        p79.encode_compact_index(len(encoded) + 1)
        + encoded
        + b"\0"
        + struct.pack("<I", SYNTHETIC_NAME_FLAGS)
    )


def _import_record(
    name_index: dict[str, int],
    class_package: str,
    class_name: str,
    outer_ref: int,
    object_name: str,
) -> bytes:
    record = p79.encode_compact_index(name_index[class_package])
    record += p79.encode_compact_index(name_index[class_name])
    record += struct.pack("<i", outer_ref)
    record += p79.encode_compact_index(name_index[object_name])
    return record


def _export_record(
    name_index: dict[str, int], spec: dict[str, object], serial_offset: int | None
) -> bytes:
    payload = spec.get("payload", b"")
    assert isinstance(payload, bytes)
    record = p79.encode_compact_index(int(spec["class_ref"]))  # type: ignore[arg-type]
    record += p79.encode_compact_index(int(spec["super_ref"]))  # type: ignore[arg-type]
    record += struct.pack("<i", int(spec["outer_ref"]))  # type: ignore[arg-type]
    record += p79.encode_compact_index(name_index[str(spec["name"])])
    record += struct.pack("<I", SYNTHETIC_OBJECT_FLAGS)
    record += p79.encode_compact_index(len(payload))
    if payload:
        assert serial_offset is not None
        record += p79.encode_compact_index(serial_offset)
    return record


def build_package(
    stem: str,
    names: tuple[str, ...],
    *,
    imports: tuple[tuple[str, str, int, str], ...] = (),
    export_specs: tuple[dict[str, object], ...] = (),
    utf16_names: bool = False,
) -> tuple[bytes, dict[str, object]]:
    """Assemble one minimal well-formed package-79 archive.

    Layout follows the order the reader enforces:
    summary(+generations) | name table | serial payloads | imports | exports.
    """
    name_index = {text: index for index, text in enumerate(names)}
    name_blob = b"".join(_name_record(text, utf16=utf16_names) for text in names)
    names_end = HEADER_SIZE + len(name_blob)

    payload_chunks: list[bytes] = []
    payload_spans: list[tuple[int, int]] = []
    export_records: list[bytes] = []
    cursor = names_end
    for spec in export_specs:
        payload = spec.get("payload", b"")
        assert isinstance(payload, bytes)
        serial_offset = cursor if payload else None
        export_records.append(_export_record(name_index, spec, serial_offset))
        if payload:
            payload_chunks.append(payload)
            payload_spans.append((cursor, cursor + len(payload)))
            cursor += len(payload)
    import_offset = cursor

    import_records = [_import_record(name_index, *entry) for entry in imports]
    import_blob = b"".join(import_records)
    # Absolute file offsets of each import's outer_ref i32 (records vary in width).
    import_outer_offsets: list[int] = []
    walk = import_offset
    for entry, record in zip(imports, import_records):
        prefix = p79.encode_compact_index(name_index[entry[0]])
        prefix += p79.encode_compact_index(name_index[entry[1]])
        import_outer_offsets.append(walk + len(prefix))
        walk += len(record)
    export_offset = import_offset + len(import_blob)

    summary = struct.pack(
        "<IIIiiiiii4Ii2i",
        PACKAGE_TAG,
        VERSION_WORD,
        0,  # package flags
        len(names),
        HEADER_SIZE,  # name_offset: names begin immediately after the summary
        len(export_specs),
        export_offset,
        len(imports),
        import_offset,
        *FIXED_GUID,
        1,  # generation count
        len(export_specs),  # latest generation: export count
        len(names),  # latest generation: name count
    )
    data = bytes(summary) + name_blob + b"".join(payload_chunks) + import_blob
    data += b"".join(export_records)
    layout: dict[str, object] = {
        "stem": stem,
        "magic_offset": 0,
        "version_word_offset": 4,
        "name_count_offset": 12,
        "payload_spans": payload_spans,
        "import_outer_refs": import_outer_offsets,
        "file_size": len(data),
    }
    return data, layout


def _patch_i32(data: bytes, offset: int, value: int) -> bytes:
    patched = bytearray(data)
    struct.pack_into("<i", patched, offset, value)
    return bytes(patched)


def build_corpus() -> dict[str, tuple[bytes, dict[str, object] | None]]:
    """Deterministic golden + corrupted corpus; committed fixtures derive from this."""
    corpus: dict[str, tuple[bytes, dict[str, object] | None]] = {}

    minimal, minimal_layout = build_package(
        "Save0",
        _SAVE_NAMES,
        imports=_SAVE_IMPORTS,
        export_specs=(_LEVEL_EXPORT,),
    )
    corpus["Save0.usa"] = (minimal, minimal_layout)

    payload_spec = {**_LEVEL_EXPORT, "payload": _synthetic_payload()}
    with_payload, payload_layout = build_package(
        "Save1",
        _SAVE_NAMES,
        imports=_SAVE_IMPORTS,
        export_specs=(payload_spec,),
    )
    corpus["Save1.usa"] = (with_payload, payload_layout)

    utf16, _utf16_layout = build_package(
        "Save2",
        _SAVE_NAMES,
        imports=_SAVE_IMPORTS,
        export_specs=(_LEVEL_EXPORT,),
        utf16_names=True,
    )
    corpus["Save2.usa"] = (utf16, None)

    def mutate(base: bytes, mutate_fn) -> bytes:
        return mutate_fn(bytearray(base))

    # Header surgery on Save0.
    corpus["bad_magic.usa"] = (
        mutate(minimal, lambda b: struct.pack_into("<I", b, 0, 0xDEADBEEF) or bytes(b)),
        None,
    )
    corpus["bad_version.usa"] = (
        mutate(minimal, lambda b: struct.pack_into("<I", b, 4, 80) or bytes(b)),
        None,
    )
    corpus["bad_licensee.usa"] = (
        mutate(
            minimal,
            lambda b: struct.pack_into("<I", b, 4, PACKAGE_VERSION | (1 << 16)) or bytes(b),
        ),
        None,
    )
    corpus["zeroed_name_count.usa"] = (
        mutate(minimal, lambda b: struct.pack_into("<i", b, 12, 0) or bytes(b)),
        None,
    )

    # Reference surgery on Save1 (its import table carries two records).
    outer_at = int(payload_layout["import_outer_refs"][1])  # type: ignore[index]
    corpus["dangling_import_outer.usa"] = (
        _patch_i32(with_payload, outer_at, 99999),
        {"patched_offset": outer_at},
    )

    # Structural damage.
    corpus["truncated_tail.usa"] = (with_payload[:-8], {"removed_bytes": 8})
    corpus["empty.usa"] = (b"", {})

    # Silent corruption probe: flip one payload bit; package-79 has no checksum,
    # so the structural reader cannot notice. repair_save exists precisely
    # because of this blind spot.
    span = payload_layout["payload_spans"][0]  # type: ignore[index]
    flip_at = int(span[0] + (span[1] - span[0]) // 2)  # type: ignore[index]
    flipped = mutate(with_payload, lambda b: b.__setitem__(flip_at, b[flip_at] ^ 0x08) or bytes(b))
    corpus["flipped_payload_bit.usa"] = (flipped, {"flipped_offset": flip_at})

    return corpus


GOLDEN_FILES = ("Save0.usa", "Save1.usa", "Save2.usa")

# Executable specification of the corrupted variants; MANIFEST.json embeds it.
CORRUPTION_CASES = (
    {
        "file": "bad_magic.usa",
        "base": "Save0.usa",
        "corruption": "package tag overwritten with 0xDEADBEEF",
        "reason_code": "header.bad_tag",
        "invariant": "save.package79.header.tag",
        "message_contains": "bad package tag",
    },
    {
        "file": "bad_version.usa",
        "base": "Save0.usa",
        "corruption": "version word rewritten from 79 to 80",
        "reason_code": "header.bad_version",
        "invariant": "save.package79.header.version",
        "message_contains": "unsupported version/licensee 80/0",
    },
    {
        "file": "bad_licensee.usa",
        "base": "Save0.usa",
        "corruption": "licensee word rewritten from 0 to 1",
        "reason_code": "header.bad_licensee",
        "invariant": "save.package79.header.licensee",
        "message_contains": "unsupported version/licensee 79/1",
    },
    {
        "file": "zeroed_name_count.usa",
        "base": "Save0.usa",
        "corruption": "summary name count zeroed (offset 12)",
        "reason_code": "header.generation_disagreement",
        "invariant": "save.package79.header.generation_consistency",
        "message_contains": "latest generation counts disagree with summary",
    },
    {
        "file": "dangling_import_outer.usa",
        "base": "Save1.usa",
        "corruption": "second import outer_ref rewritten to 99999",
        "reason_code": "table.dangling_reference",
        "invariant": "save.package79.table.reference_integrity",
        "message_contains": "is out of range",
    },
    {
        "file": "truncated_tail.usa",
        "base": "Save1.usa",
        "corruption": "final 8 bytes removed",
        "reason_code": "structure.truncated_export_table",
        "invariant": "save.package79.structure.export_table_complete",
        "message_contains": "truncated export table",
    },
    {
        "file": "empty.usa",
        "base": None,
        "corruption": "zero-byte file",
        "reason_code": "structure.truncated_summary",
        "invariant": "save.package79.structure.summary_present",
        "message_contains": "truncated package summary",
    },
)

PROBE_CASE = {
    "file": "flipped_payload_bit.usa",
    "base": "Save1.usa",
    "corruption": "one payload bit flipped mid-export",
    "reason_code": "payload.no_checksum_coverage",
    "invariant": "save.package79.payload.no_checksum_coverage",
}


def build_manifest() -> dict[str, object]:
    corpus = build_corpus()
    cases: list[dict[str, object]] = []
    labels = {"layer": "integration", "data_profile": "data-none"}
    for name in GOLDEN_FILES:
        data, _layout = corpus[name]
        cases.append(
            {
                "file": name,
                "kind": "golden",
                "package_stem": Path(name).stem,
                "expectation": "parses_and_loads",
                "invariant": "save.package79.golden_parses",
                "sha256": hashlib.sha256(data).hexdigest(),
                "size": len(data),
                "labels": labels,
            }
        )
    for case in CORRUPTION_CASES:
        data, _layout = corpus[str(case["file"])]
        cases.append(
            {
                **case,
                "kind": "corrupt",
                "expectation": "rejected",
                "sha256": hashlib.sha256(data).hexdigest(),
                "size": len(data),
                "labels": labels,
            }
        )
    data, layout = corpus[PROBE_CASE["file"]]
    cases.append(
        {
            **PROBE_CASE,
            "kind": "probe",
            "expectation": "parses_structurally_corruption_undetectable",
            "detail": (
                "package-79 carries no checksum; the structural reader accepts "
                "this file. Only the export payload sha256 changes, which is why "
                "repair_save re-saves through the native loader instead of "
                "patching bytes."
            ),
            "flipped_offset": layout["flipped_offset"] if layout else None,  # type: ignore[index]
            "sha256": hashlib.sha256(data).hexdigest(),
            "size": len(data),
            "labels": labels,
        }
    )
    return {
        "schema_version": 1,
        "format": "hp2-save-format-golden",
        "generator": "Tests/SaveFormatTests.py",
        "regenerate_command": "python3 Tests/SaveFormatTests.py --generate",
        "package_tag_hex": f"0x{PACKAGE_TAG:08x}",
        "package_version": PACKAGE_VERSION,
        "licensee_version": LICENSEE_VERSION,
        "data_profile": "data-none",
        "notes": [
            "Synthetic corpus: generic UE1 identifiers, arithmetic payloads, "
            "fixed GUIDs. No copyrighted game data.",
            "package-79 has no checksum field anywhere in the format; see the "
            "flipped_payload_bit.usa probe case.",
        ],
        "cases": cases,
    }


# ---------------------------------------------------------------------------
# Native-writer roundtrip (opt-in; item 3 of the assignment)
# ---------------------------------------------------------------------------

ROUNDTRIP_ENV = "HP2_SAVEFORMAT_ROUNDTRIP"
ROUNDTRIP_TIMEOUT_ENV = "HP2_SAVEFORMAT_ROUNDTRIP_TIMEOUT"


def _report_path(name: str) -> Path | None:
    artifact_dir = os.environ.get("HP2_ARTIFACT_DIR")
    return Path(artifact_dir) / name if artifact_dir else None


def write_report(
    name: str,
    *,
    status: str,
    invariant: str,
    reason_code: str | None = None,
    exit_reason: str = "",
    extra_artifacts: list[dict[str, str]] | None = None,
) -> Path | None:
    """Emit a report-schema-v1 JSON document; best-effort, never raises."""
    path = _report_path(name)
    if path is None:
        return None
    report: dict[str, object] = {
        "schema": 1,
        "name": path.stem,
        "status": status,
        "invariant": invariant,
        "data": {"profile": "data-none"},
        "artifacts": extra_artifacts or [],
        "command": "python3 Tests/SaveFormatTests.py",
        "exit_reason": exit_reason,
    }
    if reason_code is not None:
        report["reason_code"] = reason_code
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    except OSError:
        return None
    return path


def _discover_engine() -> Path | None:
    candidates: list[Path] = []
    explicit = os.environ.get("HP2_ENGINE_BINARY")
    if explicit:
        candidates.append(Path(explicit))
    bundle = REPOSITORY_ROOT / "dist" / "macos-arm64" / "HarryPotter2.app" / "Contents" / "MacOS"
    if bundle.is_dir():
        candidates.extend(sorted(entry for entry in bundle.iterdir() if entry.is_file()))
    for candidate in candidates:
        if candidate.is_file() and not candidate.is_symlink() and os.access(candidate, os.X_OK):
            return candidate
    return None


def _discover_data_root() -> Path | None:
    root = Path(os.environ.get("HP2_DATA_ROOT") or REPOSITORY_ROOT / "HarryPotter2" / "Unreal")
    required = ("System/Default.ini", "System/DefUser.ini")
    if all((root / relative).is_file() for relative in required):
        return root
    return None


# ---------------------------------------------------------------------------
# Contract tests
# ---------------------------------------------------------------------------


class SaveFormatContracts(unittest.TestCase):
    maxDiff = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.manifest_path = FIXTURE_DIR / "MANIFEST.json"
        cls.manifest = json.loads(cls.manifest_path.read_text())
        cls.cases_by_file = {case["file"]: case for case in cls.manifest["cases"]}  # type: ignore[index]
        cls.bytes_by_file = {
            path.name: path.read_bytes()
            for path in sorted(FIXTURE_DIR.glob("*.usa"))
        }

    def _reader(self, name: str) -> p79.PackageReader:
        return p79.PackageReader(name, self.bytes_by_file[name])

    # -- corpus integrity ---------------------------------------------------

    def test_manifest_covers_exactly_the_committed_files(self) -> None:
        listed = {str(case["file"]) for case in self.manifest["cases"]}  # type: ignore[index]
        present = set(self.bytes_by_file)
        self.assertEqual(listed, present, "invariant save.corpus.manifest_covers_files")
        for case in self.manifest["cases"]:  # type: ignore[union-attr]
            data = self.bytes_by_file[str(case["file"])]
            self.assertEqual(
                hashlib.sha256(data).hexdigest(),
                case["sha256"],
                f"invariant save.corpus.fixture_sha256 for {case['file']}",
            )

    def test_corpus_regenerates_byte_identically(self) -> None:
        for name, (data, _layout) in build_corpus().items():
            self.assertEqual(
                data,
                self.bytes_by_file[name],
                f"invariant save.corpus.generator_matches_committed for {name}",
            )

    # -- golden behaviour ---------------------------------------------------

    def test_golden_saves_parse_with_literal_versioned_header(self) -> None:
        for name in GOLDEN_FILES:
            with self.subTest(file=name):
                case = self.cases_by_file[name]
                self.assertEqual(
                    case["expectation"], "parses_and_loads"
                )
                parsed = self._reader(name).read()
                summary = parsed["summary"]
                self.assertEqual(summary["tag"], 0x9E2A83C1, "invariant save.package79.header.tag")
                self.assertEqual(summary["version"], 79, "invariant save.package79.header.version")
                self.assertEqual(summary["licensee"], 0, "invariant save.package79.header.licensee")
                self.assertEqual(
                    summary["version_word"],
                    79,
                    "invariant save.package79.header.version_word_literal",
                )
                self.assertEqual(
                    parsed["package_name"],
                    Path(name).stem,
                    "invariant save.package79.package_name_from_stem",
                )
                self.assertTrue(parsed["exports"], "invariant save.package79.has_exports")

    def test_golden_filenames_satisfy_repair_save_slot_contract(self) -> None:
        for name in GOLDEN_FILES:
            self.assertIsNotNone(
                repair_save.SAVE_NAME.fullmatch(name),
                f"invariant save.slot.naming violated by {name}",
            )

    def test_save_slot_regex_accepts_only_canonical_slots(self) -> None:
        self.assertIsNone(repair_save.SAVE_NAME.fullmatch("checkpoint.usa"))
        self.assertIsNone(repair_save.SAVE_NAME.fullmatch("Save01.usa"))
        self.assertIsNone(repair_save.SAVE_NAME.fullmatch("SaveX.usa"))

    # -- corrupted variants -------------------------------------------------

    def test_corrupt_variants_rejected_with_precise_reasons(self) -> None:
        for case in self.manifest["cases"]:  # type: ignore[union-attr]
            if case["kind"] != "corrupt":
                continue
            with self.subTest(file=case["file"], reason_code=case["reason_code"]):
                reader = self._reader(str(case["file"]))
                with self.assertRaises(p79.PackageFormatError) as caught:
                    reader.read()
                message = str(caught.exception)
                self.assertIn(
                    str(case["message_contains"]),
                    message,
                    f"invariant {case['invariant']} violated with wrong diagnostic: {message}",
                )

    def test_payload_bit_flip_is_structurally_undetectable(self) -> None:
        """Documents the format's checksum blind spot (motivation for repair_save)."""
        pristine = self._reader("Save1.usa").read()
        flipped = self._reader("flipped_payload_bit.usa").read()
        self.assertNotEqual(
            pristine["exports"][0]["serial"]["sha256"],
            flipped["exports"][0]["serial"]["sha256"],
            "invariant save.package79.payload.flip_changes_content",
        )
        self.assertNotIn(
            "checksum",
            json.dumps(flipped).lower(),
            "invariant save.package79.payload.no_checksum_coverage",
        )

    # -- native writer roundtrip (opt-in) ------------------------------------

    @unittest.skipUnless(
        os.environ.get(ROUNDTRIP_ENV, "").lower() in ("1", "true", "yes"),
        f"native writer roundtrip is opt-in; set {ROUNDTRIP_ENV}=1",
    )
    def test_native_writer_roundtrip_matches_golden_structure(self) -> None:
        engine = _discover_engine()
        data_root = _discover_data_root()
        if engine is None or data_root is None:
            write_report(
                "save_format_roundtrip.json",
                status="blocked",
                invariant="save.native.writer_roundtrip",
                reason_code="engine.binary_or_data_unavailable",
                exit_reason=(
                    f"engine={engine!r} data_root={data_root!r}; set "
                    "HP2_ENGINE_BINARY / HP2_DATA_ROOT to override discovery"
                ),
            )
            self.skipTest("native engine binary or prototype data root unavailable")

        timeout = float(os.environ.get(ROUNDTRIP_TIMEOUT_ENV, "180"))
        with tempfile.TemporaryDirectory(prefix="hp2-saveformat-roundtrip-") as temporary:
            user_root = Path(temporary) / "User"
            (user_root / "Save").mkdir(parents=True)
            (user_root / "Game.ini").write_text("[Engine.Engine]\n")
            (user_root / "User.ini").write_text("[Engine.Input]\n")
            target = user_root / "Save" / "Save0.usa"
            shutil.copyfile(FIXTURE_DIR / "Save0.usa", target)
            try:
                repair_save.repair_save(engine, data_root, user_root, target, timeout_seconds=timeout)
            except repair_save.RepairError as exc:
                write_report(
                    "save_format_roundtrip.json",
                    status="blocked",
                    invariant="save.native.writer_roundtrip",
                    reason_code="save.engine_loader_rejected_synthetic_golden",
                    exit_reason=f"repair_save failed: {exc}",
                )
                self.skipTest(f"native loader rejected the synthetic golden: {exc}")

            native = p79.PackageReader("Save0.usa", target.read_bytes()).read()

        golden = p79.PackageReader("Save0.usa", (FIXTURE_DIR / "Save0.usa").read_bytes()).read()
        self.assertEqual(native["summary"]["tag"], 0x9E2A83C1, "invariant save.package79.header.tag")
        self.assertEqual(native["summary"]["version"], 79, "invariant save.package79.header.version")
        self.assertEqual(native["summary"]["licensee"], 0, "invariant save.package79.header.licensee")
        self.assertEqual(
            sorted(native["summary"]),
            sorted(golden["summary"]),
            "invariant save.native.summary_shape_matches_golden",
        )
        self.assertEqual(
            sorted(native["regions"]),
            sorted(golden["regions"]),
            "invariant save.native.region_shape_matches_golden",
        )


def _generate() -> int:
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    corpus = build_corpus()
    for name, (data, _layout) in sorted(corpus.items()):
        (FIXTURE_DIR / name).write_bytes(data)
    (FIXTURE_DIR / "MANIFEST.json").write_text(
        json.dumps(build_manifest(), indent=2, sort_keys=True) + "\n"
    )
    print(f"wrote {len(corpus)} archives + MANIFEST.json to {FIXTURE_DIR}")
    return 0


def main(argv: list[str] | None = None) -> int:
    arguments = sys.argv[1:] if argv is None else argv
    if "--generate" in arguments:
        return _generate()

    suite = unittest.defaultTestLoader.loadTestsFromModule(sys.modules[__name__])
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    status = "pass" if result.wasSuccessful() else "fail"
    write_report(
        "save_format_tests.json",
        status=status,
        invariant="save.format.golden_corpus",
        exit_reason=(
            f"run={result.testsRun} failures={len(result.failures)} "
            f"errors={len(result.errors)} skipped={len(result.skipped)}"
        ),
    )
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main())
