//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WindowRes.rc
//
#define EPIC_OWNERDRAW                  0
#define JAPANESE                        1
#define IDICON_TextDoc                  2
#define IDC_NetworkButton               3
#define IDDIALOG_TextScroller           101
#define IDDIALOG_Language               102
#define IDDIALOG_WizardDialog           104
#define IDDIALOG_Directory              105
#define IDDIALOG_ProductInfo            116
#define IDMENU_NotifyIcon               117
#define IDMENU_Log                      118
#define IDI_ICON1                       120
#define IDI_ICON2                       121
#define IDI_ICON3                       122
#define IDI_ICON4                       123
#define IDI_ICON5                       124
#define IDI_ICON6                       125
#define IDI_ICON7                       126
#define IDI_ICON8                       127
#define IDICON_Mainframe                128
#define IDI_ICON9                       129
#define IDI_ICON10                      130
#define IDI_ICON12                      132
#define IDI_ICON13                      133
#define IDI_ICON14                      134
#define IDI_ICON15                      135
#define IDI_ICON16                      136
#define IDI_ICON17                      137
#define IDI_ICON11                      138
#define IDI_ICON18                      139
#define IDI_ICON19                      140
#define IDI_ICON20                      141
#define IDI_ICON21                      142
#define IDI_ICON22                      143
#define IDI_ICON23                      144
#define IDI_ICON24                      145
#define IDI_ICON25                      146
#define IDI_ICON26                      147
#define IDI_ICON27                      148
#define IDI_ICON28                      149
#define IDD_TEXTEDIT                    150
#define IDR_SCRIPTMENU                  151
#define IDDIALOG_FrontEndDialog         152
#define IDDIALOG_Password               153
#define IDDIALOG_FilerPageWelcome       154
#define IDDIALOG_WizardPage             155
#define IDDIALOG_FilerPageLicense       156
#define IDDIALOG_FilerPageFolder        157
#define IDDIALOG_FilerPageProgress      158
#define IDDIALOG_FilerPageDone          159
#define IDDIALOG_FrontEndPageConfigSound 159
#define IDDIALOG_FilerPageComponents    160
#define IDDIALOG_FilerPageInternet      161
#define IDDIALOG_FrontEndPageConfigVideo 161
#define IDDIALOG_FrontEndPageMainMenu   162
#define IDDIALOG_FrontEndPageSlotMenu   163
#define IDDIALOG_FrontEndPageSplash     164
#define IDDIALOG_FrontEndPageConfig     165
#define IDC_RestartMessage              257
#define IDC_RestartText                 258
#define IDC_Complete                    259
#define IDB_BITMAP_BUTTON_DOWN          312
#define IDB_BITMAP_BUTTON_UP            313
#define IDEDIT_TextEdit                 1000
#define IDICON_Connecting               1000
#define IDC_LanguageCombo               1001
#define IDC_Prompt                      1002
#define IDC_Next                        1004
#define IDC_Finish                      1005
#define IDC_PathEdit                    1006
#define IDICON_Setup                    1007
#define IDC_DirectoriesEdit             1008
#define IDC_DrivesEdit                  1009
#define IDC_ChoosePrompt                1010
#define IDC_PathTitle                   1011
#define IDEDIT_Name                     1012
#define IDC_DirectoryTitle              1013
#define IDEDIT_Password                 1014
#define IDC_DrivesTitle                 1015
#define IDC_LanguagePrompt              1016
#define IDC_LanguageList                1017
#define IDC_WelcomePrompt               1018
#define IDC_LicenseEdit                 1019
#define IDC_Browse                      1020
#define IDLABEL_Prompt                  1021
#define IDC_Progress                    1022
#define IDC_Add                         1023
#define IDC_Logo                        1024
#define IDC_Total                       1025
#define IDC_ComponentsDescription       1026
#define IDC_ComponentsPrompt            1027
#define IDC_ComponentsHolder            1028
#define IDC_DescriptionFrame            1029
#define IDC_DescriptionText             1030
#define IDC_DiskSpaceFrame              1031
#define IDC_SpaceRequiredMessage        1032
#define IDC_SpaceAvailableMessage       1033
#define IDC_SpaceRequired               1034
#define IDC_SpaceAvailable              1035
#define IDC_FolderDescription           1036
#define IDC_Folder                      1037
#define IDC_ProductText                 1038
#define IDC_VersionText                 1039
#define IDC_PublisherText               1040
#define IDC_DeveloperText               1040
#define IDC_DragItem                    1041
#define IDC_LicenseText                 1042
#define IDC_LicenseQuestion             1043
#define IDC_InstallText                 1044
#define IDC_InstallingText              1045
#define IDC_ProgressText                1046
#define IDC_TotalText                   1047
#define IDC_Installing                  1048
#define IDC_ReleaseNotes                1055
#define IDC_Reinstall                   1056
#define IDC_Uninstall                   1057
#define IDC_Web                         1058
#define IDC_PageHolder                  1061
#define IDC_ReleaseNotes2               1062
#define IDC_FolderHolder                1063
#define IDC_ReleaseNotes3               1064
#define IDC_Product                     1065
#define IDC_Version                     1066
#define IDC_Publisher                   1067
#define IDC_Developer                   1067
#define IDC_ProductHolder               1068
#define IDC_NamePrompt                  1072
#define IDC_PasswordPrompt              1073
#define IDC_Restart                     1074
#define IDC_Exit                        1075
#define IDC_Play                        1082
#define IDC_Options                     1083
#define IDC_ProductInfoHolder           1085
#define IDC_FailedMessage               1086
#define IDC_Default                     1089
#define IDC_Message                     1091
#define IDC_Divider                     1092
#define IDC_UninstallPrompt             1093
#define IDC_UninstallQuestion           1094
#define IDC_Yes                         1095
#define IDC_No                          1096
#define IDC_DependenciesFrame           1096
#define IDC_UninstallListEdit           1098
#define IDC_DetailPrompt                1099
#define IDC_DetailEdit                  1100
#define IDC_NoDrop                      1101
#define IDC_DetailNote                  1102
#define IDC_SplitNS                     1103
#define IDC_RenderPrompt                1104
#define IDC_SplitWE                     1105
#define IDC_RenderList                  1106
#define IDC_RenderNote                  1107
#define IDC_SafeModePrompt              1108
#define IDC_SafeOptions                 1109
#define IDC_Run                         1110
#define IDC_NoSound                     1111
#define IDC_SafeMode                    1112
#define IDC_No3DSound                   1113
#define IDC_Compatible                  1114
#define IDC_Video                       1115
#define IDC_No3dVideo                   1116
#define IDC_All                         1117
#define IDC_DriverText                  1118
#define IDC_Res                         1119
#define IDC_Card                        1120
#define IDC_Window                      1121
#define IDC_DriverInfo                  1122
#define IDC_D3DRenderer                 1122
#define IDC_ResetConfig                 1123
#define IDC_WebButton                   1124
#define IDC_SoftwareRenderer            1124
#define IDC_NoProcessor                 1125
#define IDC_NoJoy                       1126
#define IDC_ResolutionList              1126
#define IDC_RICHEDIT2                   1127
#define IDC_ConfigVideoPrompt           1127
#define IDC_SoundVolumeSlider           1128
#define IDC_Resolution                  1128
#define IDC_Software                    1129
#define IDC_MusicVolumeSlider           1129
#define IDC_Hardware                    1130
#define IDC_ConfigVideo                 1131
#define IDC_ConfigSound                 1132
#define IDC_ConfigSoundPrompt           1132
#define IDC_Hand                        1133
#define IDC_SoundVolume                 1133
#define IDC_MusicVolume                 1134
#define IDC_MLow                        1135
#define IDC_SLow                        1136
#define IDC_SHi                         1137
#define IDC_MHi                         1138
#define IDICON_PropertySheet            1206
#define IDICON_Palette                  1257
#define IDC_ZoomIn                      1270
#define IDC_Draw                        1280
#define IDC_Crosshair                   1290
#define IDC_ZoomOut                     1310
#define IDC_LittlePointer               1423
#define IDC_LittleArrows                1442
#define IDC_SplitALL                    1443
#define IDC_SplitWE1                    1443
#define IDDIALOG_Restart                2011
#define IDDIALOG_FilerPageAutoPlay      2012
#define IDDIALOG_FailedRequirement      2013
#define IDDIALOG_FilerPagePreInstall    2014
#define IDDIALOG_FilerPageUninstall     2015
#define IDDIALOG_FilerPageUninstallComponents 2016
#define IDDIALOG_ConfigPageRenderer     2017
#define IDDIALOG_ConfigPageDetail       2018
#define IDDIALOG_ConfigPageFirstTime    2019
#define IDDIALOG_ConfigPageSafeMode     2020
#define IDDIALOG_ConfigPageSafeOptions  2021
#define IDDIALOG_ConfigPageDriver       2022
#define IDC_OK                          3000
#define IDC_Slot1                       3001
#define IDC_Slot2                       3002
#define IDC_Slot3                       3003
#define IDC_Slot4                       3004
#define IDC_Slot5                       3005
#define IDC_Slot6                       3006
#define IDC_Back                        3007
#define IDC_Config                      3019
#define IDC_LoadGame                    3020
#define IDC_NewGame                     3021
#define IDC_Instructions                3022
#define IDC_JoystickConfig              3023
#define IDC_VideoConfig                 3024
#define IDC_SoundConfig                 3025
#define IDMENU_BrowserActor_Context     15111
#define IDMENU_2DShapeEditor            15150
#define IDMN_2DSE_OPEN_IMAGE            16000
#define IDMN_AB_NEW_CLASS               19700
#define IDBM_CHECKBOX_OFF               29750
#define IDBM_CHECKBOX_ON                29751
#define IDICON_HomePage                 32536
#define IDICON_FolderClosed             32544
#define IDICON_FolderOpen               32545
#define IDICON_Editor                   32546
#define IDICON_TheInternet              32548
#define ID_NotifyShowLog                40002
#define ID_LogFileExit                  40004
#define ID_NotifyExit                   40005
#define ID_LogAdvancedOptions           40006
#define ID_NotifyAdvancedOptions        40007
#define ID_CANCEL                       40008
#define IDMN_2DSE_FileOpen              40202
#define IDMN_2DSE_FilleSave             40203
#define IDMN_2DSE_FilleSaveAs           40204
#define IDMN_2DSE_NEW                   40206
#define IDMN_2DSE_SPLIT_SIDE            40207
#define IDMN_2DSE_DELETE_VERTEX         40208
#define IDMN_2DSE_PROCESS_SHEET         40209
#define IDMN_2DSE_PROCESS_EXTRUDE       40210
#define IDMN_2DSE_PROCESS_REVOLVE       40211
#define IDMN_2DSE_DELETE_IMAGE          40220
#define IDMN_AB_DELETE                  40238
#define IDMN_AB_DEF_PROP                40241
#define IDMN_AB_EDIT_SCRIPT             40242
#define IDMN_2DSE_NEW_SHAPE             40267
#define ID_FileExit                     40300

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1132
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
